FROM centos

RUN yum update -y \
 && yum install -y sudo

RUN \
    yum install -y epel-release && \
    yum install -y nginx
    
RUN sudo systemctl enable nginx

RUN mkdir nginx_test
RUN echo "1234" >> /nginx_test/index.html
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/start.sh /start.sh
RUN chmod +x /start.sh

CMD /start.sh